### ISSUE TITLE
Logs do not write at all on Windows

### ISSUE THREAD

**Issue by kj4awr** [hrfee/jfa-go#168]
I have been trying to troubleshoot for an hour or so now email not working at all. Every time I try to look at the logs the file is completely empty. I have tried running regularly and as admin on Windows 10 and never get a single letter to write to the logs.
Any help would be appreciated and also if you can add a way to customize the log location so it doesn't go to %temp%  that would be great.

**Comment by hrfee** [comment]
Really sorry about such a late reply, hope you're still interested in getting this to work. Although my testing is limited as i'm running the Windows version through wine, the latest unstable version succeeds in writing logs to the temp location. Which version was this not working with? If you can't see the logs you can check in Settings > About.

**Comment by hrfee** [comment]
Also, in another issue I noticed that errors regarding to writing to the log file were being ignored. I fixed that and put a new unstable build up. Could you try running it in a terminal (this way you should see the program output)? You can do this by Shift-Right clicking the folder the executable's stored in in your explorer window and pressing "Open Powershell window here", then typing jfa-go.exe and pressing Enter.

**Comment by kimboslice99** [comment]
this issue is still present, attempting to run the windows version via a command prompt doesnt show anything and simply starts the tray icon

**Comment by kimboslice99** [comment]
Workaround: run jfa-go start from a prompt, now it logs

**Comment by hrfee** [comment]
This should be fixed now, logs won't show up when you start a tray version via command prompt, but will be output to %TEMP%/jfa-go.log, and crash reports work now and get placed in the same folder.
