### ISSUE TITLE
split routing invite page (/accounts/invite) from admin page (/accounts) 

### ISSUE THREAD

**Issue by mezzovide** [hrfee/jfa-go#49]
what i tried to do was making 
`/accounts` only available from LAN `http://192.168.x.x/accounts`
and `accounts/invite` available to WAN `https://test.com/invite`
but i think its not possible because when i try to access the `https://test.com/invite/xxx` from WAN this is happen

![Untitled](https://user-images.githubusercontent.com/2650084/107507173-c4dbad00-6bd1-11eb-8b47-87a712fbdf2f.png)

because /accounts isnt accesible from WAN. 
i think this kind of configuration should be possible, because it will reduce security risk if /accounts (admin page) not available to public, only /invite.

**Comment by hrfee** [comment]
This works perfectly for me already with this configuration in nginx, it shouldn't be too hard to adapt to Apache (which you use iirc):
```nginx
location / {
    proxy_pass http://ip-address:8056;
    allow 192.168.1.0/24; # This is my local network subnet
    deny all;
}
location /invite {
    proxy_pass http://ip-address:8056/invite;
    allow all;
}
```
Also, could you post your proxy config? I might be able to help modify it.

**Comment by mezzovide** [comment]
yeah, i guess that would work too. btw, im using ur latest git build after commit `f72def0` something broken i think.
```
[ui]
url_base        = /accounts
[invite_emails]
url_base   = https://test.com/invite
```
```
<VirtualHost *:443>

    ServerName test.com
    ProxyPreserveHost On

    ProxyPass "/" "http://localhost:8096/"                             #jellyfin
    ProxyPassReverse "/" "http://localhost:8096/"                #jellyfin

    ProxyPass "/accounts" "http://localhost:8056/accounts"                   #jfa-go
    ProxyPassReverse "/accounts" "http://localhost:8056/accounts"      #jfa-go

    ProxyPass "/invite" "http://localhost:8056/invite"                 #jfa-go invite page
    ProxyPassReverse "/invite" "http://localhost:8056/invite"    #jfa-go invite page

```
<pre>
[DEBUG] 13:34:06 api.go:586: Generating new invite
[DEBUG] 13:34:06 api.go:615: foJ3d2AkmEAAvXwnhvVb2g: Sending invite email
[INFO] 13:34:08 foJ3d2AkmEAAvXwnhvVb2g: Sent invite email to user@user.com
[GIN/DEBUG] 13:34:08: POST(/accounts/invites) => 200 in 2.1376265s;
[DEBUG] 13:34:08 auth.go:89: Auth succeeded
[DEBUG] 13:34:08 api.go:788: Invites requested
[GIN/DEBUG] 13:34:08: GET(/accounts/invites) => 200 in 1.0007ms;
[GIN/DEBUG] 13:34:17: GET(/invite/foJ3d2AkmEAAvXwnhvVb2g) => 200 in 4.0017ms;
[GIN/DEBUG] 13:34:17: GET(/accounts/css/bundle.css) => 200 in 0s;
[GIN/DEBUG] 13:34:17: GET(/accounts/css/remixicon.css) => 200 in 0s;
[GIN/DEBUG] 13:34:17: GET(/invite/css/remixicon.woff2?t=1590207869815) => 200 in 0s;
<b>[GIN/DEBUG] 13:34:17: GET(/invite/0xd50dc0/lang/form) => 404 in 5.001ms;
[GIN/DEBUG] 13:34:17: GET(/invite/0xd50dc0/favicon-32x32.png) => 404 in 4.0006ms;
[GIN/DEBUG] 13:34:17: GET(/invite/0xd50dc0/favicon-16x16.png) => 404 in 3.9996ms;
[GIN/DEBUG] 13:34:17: GET(/invite/0xd50dc0/apple-touch-icon.png) => 404 in 2.9981ms;</b>
[GIN/DEBUG] 13:34:25: GET(/invite/foJ3d2AkmEAAvXwnhvVb2g) => 200 in 3.999ms;
[DEBUG] 13:34:26 auth.go:89: Auth succeeded
[DEBUG] 13:34:26 api.go:788: Invites requested
[GIN/DEBUG] 13:34:26: GET(/accounts/invites) => 200 in 1.0007ms;
[DEBUG] 13:34:26 auth.go:89: Auth succeeded
[DEBUG] 13:34:26 api.go:979: Users requested
[GIN/DEBUG] 13:34:26: GET(/accounts/users) => 200 in 0s;
[GIN/DEBUG] 13:34:26: GET(/invite/js/form.js) => 200 in 1.0007ms;
[GIN/DEBUG] 13:34:26: GET(/invite/css/bundle.css) => 200 in 997.3µs;
[GIN/DEBUG] 13:34:27: GET(/invite/css/remixicon.css) => 200 in 1.0122ms;
[GIN/DEBUG] 13:34:29: GET(/invite/css/remixicon.woff2?t=1590207869815) => 200 in 0s;
[DEBUG] 13:34:39 daemon.go:37: Daemon: Checking invites
<b>[GIN/DEBUG] 13:34:47: POST(/invite/0xd50dc0/newUser) => 404 in 2.9992ms;</b>
</pre>

**Comment by mezzovide** [comment]
oh and can u make windows build with `.7z` or `.zip` instead of `tar.gz`. would be a little bit easier not to unpackage twice :)

**Comment by hrfee** [comment]
`ProxyPass "/accounts" "http://localhost:8056/accounts"                   #jfa-go`
this line was the culprit, before yesterday jfa-go didn't actually serve on the URL Base and relied on the reverse proxy to rewrite it. I added it in f72def0399d73250c7de0bac8d2bbb237401a7f5, so if you update it should hopefully work perfectly.

**Comment by hrfee** [comment]
Didn't see you were already using it. Anyway, having separate subfolders to `accounts/` and `invite/` probably won't work. You can still restrict access to the admin page without separating them though.

**Comment by hrfee** [comment]
```apache
ProxyPass "/accounts" "http://localhost:8056/accounts"                   #jfa-go
ProxyPassReverse "/accounts" "http://localhost:8056/accounts"      #jfa-go

ProxyPass "/accounts/invite" "http://localhost:8056/accounts/invite"                 #jfa-go invite page
ProxyPassReverse "/accounts/invite" "http://localhost:8056/accounts/invite"    #jfa-go invite page

<Location /accounts>
    Require ip 192.168 #Local network
</Location>
<Location /accounts/invite>
    Require all granted
</Location>
```
This should work to restrict it.

**Comment by mezzovide** [comment]
```
[ui]
url_base        = /accounts
[invite_emails]
url_base   = https://test.com/accounts/invite
```
```
<VirtualHost *:443>

    ServerName test.com
    ProxyPreserveHost On

    ProxyPass "/" "http://localhost:8096/"                             #jellyfin
    ProxyPassReverse "/" "http://localhost:8096/"                #jellyfin

    ProxyPass "/accounts" "http://localhost:8056/accounts"                   #jfa-go
    ProxyPassReverse "/accounts" "http://localhost:8056/accounts"      #jfa-go
```
using this also not working. stuck when click `create account` in the `accounts/invite/xxx` page
```
[DEBUG] 19:21:16 api.go:586: Generating new invite
[GIN/DEBUG] 19:21:16: POST(/accounts/invites) => 200 in 7ms;
[DEBUG] 19:21:16 auth.go:89: Auth succeeded
[DEBUG] 19:21:16 api.go:788: Invites requested
[GIN/DEBUG] 19:21:16: GET(/accounts/invites) => 200 in 1.0004ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/mmbSbhaRKqtUohP7J2oL5P) => 200 in 7.0012ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/css/bundle.css) => 200 in 1.0036ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/css/remixicon.css) => 200 in 1.0036ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/css/bundle.css) => 200 in 0s;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/js/form.js) => 200 in 13ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/css/remixicon.css) => 200 in 0s;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/css/remixicon.woff2?t=1590207869815) => 200 in 0s;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/0xe20dc0/lang/form) => 404 in 4.0003ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/0xe20dc0/favicon-32x32.png) => 404 in 3.9993ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/css/remixicon.woff2?t=1590207869815) => 206 in 1.0021ms;
[GIN/DEBUG] 19:21:17: GET(/accounts/invite/0xe20dc0/apple-touch-icon.png) => 404 in 5.0023ms;
[GIN/DEBUG] 19:21:18: GET(/accounts/invite/0xe20dc0/favicon-16x16.png) => 404 in 3.9998ms;
[GIN/DEBUG] 19:21:53: POST(/accounts/invite/0xe20dc0/newUser) => 404 in 3.9995ms;
```
and then i tried with this too. also no luck
```
<VirtualHost *:443>

    ServerName test.com
    ProxyPreserveHost On

    ProxyPass "/" "http://localhost:8096/"                             #jellyfin
    ProxyPassReverse "/" "http://localhost:8096/"                #jellyfin

    ProxyPass "/accounts" "http://localhost:8056"                   #jfa-go
    ProxyPassReverse "/accounts" "http://localhost:8056"      #jfa-go
```
![Untitled](https://user-images.githubusercontent.com/2650084/107768504-208c6e80-6d69-11eb-8668-1b1d85b876cb.png)

**Comment by mezzovide** [comment]
> 
> 
> ```apache-config
> ProxyPass "/accounts" "http://localhost:8056/accounts"                   #jfa-go
> ProxyPassReverse "/accounts" "http://localhost:8056/accounts"      #jfa-go
> 
> ProxyPass "/accounts/invite" "http://localhost:8056/accounts/invite"                 #jfa-go invite page
> ProxyPassReverse "/accounts/invite" "http://localhost:8056/accounts/invite"    #jfa-go invite page
> 
> <Location /accounts>
>     Require ip 192.168 #Local network
> </Location>
> <Location /accounts/invite>
>     Require all granted
> </Location>
> ```
> 
> This should work to restrict it.

Still stuck when i click `create account`
```
[INFO] 19:37:02 Starting router @ 0.0.0.0:8056
[GIN/DEBUG] 19:37:09: GET(/accounts) => 200 in 4.9989ms;
[GIN/DEBUG] 19:37:09: GET(/accounts/css/remixicon.css) => 200 in 0s;
[GIN/DEBUG] 19:37:09: GET(/accounts/css/bundle.css) => 200 in 0s;
[DEBUG] 19:37:10 auth.go:185: Token requested (refresh token)
[DEBUG] 19:37:10 auth.go:201: getTokenRefresh: Invalid token
[GIN/DEBUG] 19:37:10: GET(/accounts/token/refresh) => 400 in 1.0009ms;
[GIN/DEBUG] 19:37:10: GET(/accounts/lang/admin) => 404 in 6.0015ms;
[INFO] 19:37:14 Token requested (login attempt)
[DEBUG] 19:37:14 auth.go:165: Token generated for user "accounts"
[GIN/DEBUG] 19:37:14: GET(/accounts/token/login) => 200 in 24ms;
[DEBUG] 19:37:14 auth.go:89: Auth succeeded
[DEBUG] 19:37:14 api.go:788: Invites requested
[GIN/DEBUG] 19:37:14: GET(/accounts/invites) => 200 in 2.0013ms;
[GIN/DEBUG] 19:37:18: GET(/accounts/invite/mmbSbhaRKqtUohP7J2oL5P) => 200 in 5.0028ms;
[GIN/DEBUG] 19:37:18: GET(/accounts/invite/0xe20dc0/lang/form) => 404 in 3.9995ms;
[GIN/DEBUG] 19:37:18: GET(/accounts/invite/0xe20dc0/favicon-32x32.png) => 404 in 5.9995ms;
[GIN/DEBUG] 19:37:19: GET(/accounts/invite/0xe20dc0/favicon-16x16.png) => 404 in 3.9997ms;
[GIN/DEBUG] 19:37:25: POST(/accounts/invite/0xe20dc0/newUser) => 404 in 4.0032ms;
```

**Comment by hrfee** [comment]
One of the issues was due to missing parentheses (lmao), and I believe i fixed the `/accounts/lang/admin` 404 as well in 4c653fe. It should be available in like 10 minutes, hopefully it should be fixed.

**Comment by hrfee** [comment]
Also, this is the correct apache configuration to stop it blocking CSS and other resources:
```apache
    ProxyPreserveHost On
    ProxyPass /accounts http://localhost:8056/accounts
    ProxyPassReverse /accounts http://localhost:8056/accounts

    ProxyPass /accounts/invite http://localhost:8056/accounts/invite
    ProxyPassReverse /accounts/invite http://localhost:8056/accounts/invite
    <Location /accounts>
        Require ip 192.168
    </Location>
    <Location /accounts/>
        Require all granted
    </Location>
    <Location /accounts/invite>
        Require all granted
    </Location>
```

**Comment by mezzovide** [comment]
fix confirmed. and i dont think u need these 
```
    ProxyPass /accounts/invite http://localhost:8056/accounts/invite
    ProxyPassReverse /accounts/invite http://localhost:8056/accounts/invite
```
if u already using
```
    ProxyPass /accounts http://localhost:8056/accounts
    ProxyPassReverse /accounts http://localhost:8056/accounts
```
since its already recursive.
so one thing left is this issue #50. still happening in the latest build.
thanks!
